"""initial sqlite schema

Revision ID: d4c35787e379
Revises: 
Create Date: 2026-07-14 23:49:44.511805
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd4c35787e379'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('root_path', sa.String(length=1024), nullable=False),
    sa.Column('type', sa.Enum('book', 'comic', 'mixed', name='sourcetype'), nullable=False),
    sa.Column('auto_scan', sa.Boolean(), nullable=False),
    sa.Column('scan_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_path')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('books',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('rel_path', sa.String(length=2048), nullable=False),
    sa.Column('dir_path', sa.String(length=2048), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('format', sa.Enum('txt', 'epub', 'pdf', 'mobi', 'comic', name='bookformat'), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('cover_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('active', 'missing', name='bookstatus'), nullable=False),
    sa.Column('chapter_count', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'rel_path', name='uq_book_source_path')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_dir_path'), ['dir_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_format'), ['format'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_rel_path'), ['rel_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_status'), ['status'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('sub_path', sa.String(length=1024), nullable=True),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_id', 'sub_path', name='uq_permission_scope')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_user_id'), ['user_id'], unique=False)

    op.create_table('reading_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('font_family', sa.String(length=128), nullable=False),
    sa.Column('font_size', sa.Integer(), nullable=False),
    sa.Column('line_height', sa.Float(), nullable=False),
    sa.Column('margin', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('scan_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='scanstatus'), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('added', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_tasks_source_id'), ['source_id'], unique=False)

    op.create_table('shelves',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_shelf_user_name')
    )
    with op.batch_alter_table('shelves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelves_user_id'), ['user_id'], unique=False)

    op.create_table('book_metadata',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('subtitle', sa.String(length=512), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('publisher', sa.String(length=256), nullable=True),
    sa.Column('isbn', sa.String(length=32), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('douban_id', sa.String(length=32), nullable=True),
    sa.Column('source_provider', sa.Enum('douban', 'google', 'openlibrary', 'manual', name='metadataprovidername'), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id')
    )
    with op.batch_alter_table('book_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_metadata_isbn'), ['isbn'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_metadata_title'), ['title'], unique=False)

    op.create_table('chapters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('location', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'idx', name='uq_chapter_book_idx')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapters_book_id'), ['book_id'], unique=False)

    op.create_table('reading_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('location', sa.String(length=1024), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('chapter_idx', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_progress_user_book')
    )
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_progress_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_progress_user_id'), ['user_id'], unique=False)

    op.create_table('shelf_books',
    sa.Column('shelf_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shelf_id', 'book_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelf_books')
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_reading_progress_book_id'))

    op.drop_table('reading_progress')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapters_book_id'))

    op.drop_table('chapters')
    with op.batch_alter_table('book_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_metadata_title'))
        batch_op.drop_index(batch_op.f('ix_book_metadata_isbn'))

    op.drop_table('book_metadata')
    with op.batch_alter_table('shelves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelves_user_id'))

    op.drop_table('shelves')
    with op.batch_alter_table('scan_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_tasks_source_id'))

    op.drop_table('scan_tasks')
    op.drop_table('reading_settings')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_permissions_source_id'))

    op.drop_table('permissions')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_status'))
        batch_op.drop_index(batch_op.f('ix_books_source_id'))
        batch_op.drop_index(batch_op.f('ix_books_rel_path'))
        batch_op.drop_index(batch_op.f('ix_books_format'))
        batch_op.drop_index(batch_op.f('ix_books_file_hash'))
        batch_op.drop_index(batch_op.f('ix_books_dir_path'))

    op.drop_table('books')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('sources')
    # ### end Alembic commands ###
